import Link from "next/link";
export const metadata = {
    title: "Create Next Blog Page App",
    description: "Generated by create next app",
};

async function productlist() {
    let data = await fetch("https://jsonplaceholder.typicode.com/users")
    data = await data.json();
    return data;

}

export default async function Home() {

    let userlist = await productlist();
    //console.log(userlist);
    return (
        <div>
            <h1>Product  List Page</h1>
            <Link href={"/"}>Home</Link>

            <ul className="list-group">
                {
                    userlist.map((item) => {
                        return (<Link href={"/productlist/"+item.id} target="_blank" key={item.id}><li className="list-group-item" >{item.name}</li></Link>)
                    })
                }
            </ul>
        </div>
    );
}

