import Link from "next/link";
import styles from "./page.module.css";

export const metadata = {
    title: "Create Next Blog Page App",
    description: "Generated by create next app",
  };

export default function Home() {
  return (
    <main className={styles.main}>

 <p className="d-inline-flex gap-1">
  <a className="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Link with href
  </a>
  <button className="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Button with data-bs-target
  </button>
</p>
<div className="collapse" id="collapseExample">
  <div className="card card-body">
    Some placeholder content for the collapse component. This panel is hidden by default but revealed when the user activates the relevant trigger.
  </div>
</div>

  
      <Link href={"/"}>Home</Link>
    </main>

  );
}

